### ISSUE TITLE
Multiple domain support

### ISSUE THREAD

**Issue by adrianofoschi** [xcv58/Custom-JavaScript-for-Websites-2#29]
Is possibile to set the same custom script for multiple domains?

**Comment by xcv58** [comment]
@adrianofoschi It's not supported yet. Due to the reasons: https://github.com/xcv58/Custom-JavaScript-for-Websites-2/issues/5#issuecomment-344813153

But I have a proposal to support inject custom code in all domains. Could you provide your feedback?
