### ISSUE TITLE
Extra scripts dialog broken

### ISSUE THREAD

**Issue by Vermeille** [xcv58/Custom-JavaScript-for-Websites-2#42]
Hello,

When the first semicolon is typed into the Extra Scripts dialog box, it is changed to a \n automatically, which is surprising, and, I guess, not intended.

I fail to load some scripts (even when they have the correct MIME type) for unknown reasons (maybe related to that). If a script fails to load, is it possible to display the error in the console?

Have a great day!

**Comment by xcv58** [comment]
I'm sorry for the inconvenience. There is a workaround to fix this. You can write correct format in an editor and copy paste to the input box.

I'll fix this bug as soon as possible.

Thank you!

**Comment by Vermeille** [comment]
Thank you for your quick answer and work around!

**Comment by xcv58** [comment]
Fixed in #44
