### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by angeliski** [xcv58/Custom-JavaScript-for-Websites-2#44]
I install the extension, but does'nt work. I see the console, but nothing is printed, for any website.
I use the old extension and don't have problem. Any sugestion?
Chrome: Version 64.0.3282.167 64 bits
OS: Mac Sierra 10.12.6

**Comment by angeliski** [comment]
Hey @xcv58 , I have the get I work around:
![cjs](https://user-images.githubusercontent.com/1574240/36488018-1fce42d2-1701-11e8-8baa-984d3f616e9e.gif)
When I remove the content of "External Scripts" the cjs work. 

Can you check that?

**Comment by xcv58** [comment]
I'll try to reproduce this bug. Thanks for reporting this.

**Comment by mikegee** [comment]
I was having the same trouble. The workaround shown got console output to show up for me. Including jQuery also got it to work.

Here's the noise in the console when it isn't working, in case that's helpful:

<img width="675" alt="screen shot 2018-03-03 at 9 04 38 am" src="https://user-images.githubusercontent.com/14068/36935158-001131e8-1ec2-11e8-82ac-2eb1fdea4286.png">

**Comment by xcv58** [comment]
Thanks for your feedback. @angeliski @mikegee  Sorry for the inconvenience caused by the bug. 

Could you please check the latest version v3.1.6?

And I open #45 to improve the workflow for the external script.

**Comment by mikegee** [comment]
> Sorry for the inconvenience caused by the bug.

No worries. Thanks for your work on this project.

**Comment by xcv58** [comment]
Thanks, @mikegee for understanding. Could you please confirm whether the v3.1.6 works for you when you have time?

**Comment by angeliski** [comment]
Hey @xcv58 , thank you for your fast response. Work for me in v3.1.6 :)

**Comment by mikegee** [comment]
3.1.6 doesn't have this bug for me either. Thanks!

**Comment by xcv58** [comment]
Thanks for confirming! @mikegee @angeliski
