### ISSUE TITLE
How to replace text in website?

### ISSUE THREAD

**Issue by pingme998** [xcv58/Custom-JavaScript-for-Websites-2#471]
Please help me, I'm not good at javascript, I need a script to replace text inside a website with Custom-JavaScript-for-Websites-2.

For example, every time I reload the website I need to find the sentence "Capture Verification Unsuccessful" within the webpage and replace it with "Capture Verification Successful"

If you are too busy. Please give any hint to fix my problem.

**Comment by xcv58** [comment]
I suggest you search on this topic: https://www.google.com/search?q=stackoverflow+js+replace+text+on+web+page&sxsrf=ALeKk007NQB0jv84hpKKEgZHmf0q9sLotg%3A1625066332675&source=hp&ei=XIvcYNCJJLOTwbkPp92ViAU&iflsig=AINFCbYAAAAAYNyZbBmFy1VJOdh5Jrbkm1OecqwDUcIK&oq=stackoverflow+js+replace+text+on+web+page&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEAoQoAEyBQghEKsCOgUIABCxAzoICAAQsQMQgwE6CAguELEDEIMBOgsILhCxAxDHARCjAjoCCAA6DgguELEDEMcBEKMCEJMCOggIABCxAxDJAzoFCAAQkgM6CAguELEDEJMCOgUILhCxAzoICC4QxwEQrwE6BAgAEAo6CAgAEBYQChAeOgYIABAWEB46CQgAEMkDEBYQHjoICAAQCBANEB46CAghEBYQHRAeUNQCWK5GYORGaABwAHgCgAGpAogBjiqSAQcxOS4xNi41mAEAoAEBqgEHZ3dzLXdpeg&sclient=gws-wiz&ved=0ahUKEwjQp_br07_xAhWzSTABHaduBVEQ4dUDCAk&uact=5

And try a smaller piece to start.
