### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by adrianofoschi** [xcv58/Custom-JavaScript-for-Websites-2#53]
Hi, I used the extension for months but it doesn't work anymore apparrently without a reason.
I insertend an alert('foo') in page script but it doesn't appear on page.

For example if I try to add a script on github I see this error in console:

Refused to execute script from 'https://github.com/undefined' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

That depends from extension. The error appear only when cjs is enabled.

**Comment by xcv58** [comment]
Thanks, @adrianofoschi I can't reproduce the bug on my laptop.

Does it work for other websites? Could you please tell me your operating system version and chrome version?

**Comment by adrianofoschi** [comment]
It worked with my old-saved scripts but If I edit one it saves it but it executes the old script.
It happens with every website.

I tried on 2 systems, with 2 different google accounts:
- Linux 4.17.5 (ArchLinux 64 bit), Chrome 63.0.3239.132 (Official Build) (64 bit)
- Windows 10 (Pro 64 bit), Chrome 67.0.3396.99 (Official Build) (64 bit)

**Comment by xcv58** [comment]
I think you may forget to click the `Save` button at the top left.
![image](https://user-images.githubusercontent.com/503123/42833258-729b9950-89a8-11e8-8bdf-2438368258ad.png)
