### ISSUE TITLE
Add Support for CSS - Feature Request

### ISSUE THREAD

**Issue by samarpw** [xcv58/Custom-JavaScript-for-Websites-2#58]
Please add CSS editor to add custom styles. thanks

**Comment by xcv58** [comment]
I suggest this extension https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe

It focuses on the CSS only.

**Comment by samarpw** [comment]
This extension https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe is heavy 1.85Mb bloatware we don't need that much features. We Just need simple CSS editor in your extension which I think can easily be added. I'm not developer otherwise I would have enhanced your extension myself.

So, I request you please add CSS Editor Feature/Functionality. It will become perfect extension. thanks

**Comment by xcv58** [comment]
Thanks, I'll investigate how to do that.

**Comment by xcv58** [comment]
@samarpw the v3.2.1 has css style support. It just highlights the code you wrote into css way. Not a real css support.
