### ISSUE TITLE
Can not load data

### ISSUE THREAD

**Issue by adamtaylor13** [xcv58/Custom-JavaScript-for-Websites-2#61]
Got this message today when opening the app:
Tried opening in a new page, to no avail.

There doesn't seem to be any information related to this so I'm not sure what information would be pertinent.

![image](https://user-images.githubusercontent.com/2922753/50983675-8ee50f80-14c5-11e9-8b80-0123c90ea894.png)

Also found this in the console, but not sure if it relates to the extension:
![image](https://user-images.githubusercontent.com/2922753/50983767-ceabf700-14c5-11e9-8e73-e5ff48dda072.png)

**Comment by KyleKing** [comment]
I ran into the same issue about 10 am this morning. Chrome `71.0.3578.98` on Windows 7. The stack trace points to this function (the `return n.apply(this, arguments)` in particular):

```js
        t.getHosts = (()=>{
            var n = i(function*(n) {
                const t = yield chrome.storage.sync.get({
                    hosts: []
                });
                if (Array.isArray(t.hosts) && t.hosts.length > 0)
                    return t.hosts;
                const {hosts: r=[]} = JSON.parse(window.localStorage.getItem(n) || "{}");
                return r
            });
            return function(t) {
                return n.apply(this, arguments)
            }
        }
```

```
run.js:formatted:349 Uncaught (in promise) TypeError: Illegal invocation: Function must be called on an object of type StorageArea
    at Promise (run.js:formatted:349)
    at new Promise (<anonymous>)
    at Object.r [as get] (run.js:formatted:347)
    at run.js:formatted:288
    at Generator.next (<anonymous>)
    at e (run.js:formatted:221)
    at run.js:formatted:233
    at new Promise (<anonymous>)
    at run.js:formatted:218
    at t.getHosts (run.js:formatted:297)
```

**Comment by xcv58** [comment]
I have the same issue on macOS, Chrome `Version 72.0.3610.2 (Official Build) dev (64-bit)`

**Comment by xcv58** [comment]
This issue related to https://github.com/KeithHenry/chromeExtensionAsync/issues/10

**Comment by adamtaylor13** [comment]
So this should be fixed with this PR? https://github.com/KeithHenry/chromeExtensionAsync/issues/10#issuecomment-444265079

**Comment by okom3pom** [comment]
Same Windows 10 -> Version 71.0.3578.98 (Build officiel) (64 bits)

Thx for your job

**Comment by xcv58** [comment]
The https://github.com/KeithHenry/chromeExtensionAsync/issues/10#issuecomment-444265079 will fix this bug. But they haven't released the fix yet. I will make a local copy for it to fix our problem in the next few hours.

**Comment by xcv58** [comment]
Can you upgrade to `v3.3.0` to see whether it fix the bug?

**Comment by adamtaylor13** [comment]
@xcv58 That fixed it!

**Comment by xcv58** [comment]
Thank you all for reporting this and confirming the fix.

**Comment by okom3pom** [comment]
Fixed for me too 
Thank again
