### ISSUE TITLE
break in proper functionality of a site

### ISSUE THREAD

**Issue by iriman** [xcv58/Custom-JavaScript-for-Websites-2#62]
I was testing some stuff for openstreetmap.org with cjs on chrome, but it made me surprised by changing preview button into save!  :)

Steps to reproduce:

1. Go to openstreetmap.org
2. Create a new javascript rule. Mine is this:

    ```
    $(".changeset-comments p").attr("dir","auto");
    $(".changeset-comments p").css({'text-align': 'start'});
    $(".browse-section h4:first-of-type").attr("dir","auto");
    $(".diary_post .post_heading h2").attr("dir","auto");
    $(".diary_post .richtext > p , .comments .richtext > p").attr("dir","auto");
    $(".diary_post .richtext > p , .comments .richtext > p").css({'text-align': 'start'});
**3. Also select one of jquery versions**
4. Now go to https://www.openstreetmap.org/diary/new (needs an account)
5. Write something and hit `preview` button. Diary will be saved!
**6. If instead of jquery... I choose `none`, there is no problem.**

**Comment by xcv58** [comment]
It's highly possible that the website openstreetmap.org has jQuery already. And you inject another jQuery with a different version (which is not necessary).

I think just don't inject external jQuery will work.

**Comment by iriman** [comment]
Yes, it's working without injecting jquery.
Maybe it would be useful if it was possible to be notified about such possible conflicts. thanks.

**Comment by xcv58** [comment]
Thanks for confirming.

It's really hard to do so because some websites may use async load and different libraries have different way to check whether it exists.
