### ISSUE TITLE
Dark Mode-Friendly Icon

### ISSUE THREAD

**Issue by KyleKing** [xcv58/Custom-JavaScript-for-Websites-2#63]
Would you be open to changes to the CJS icon? Chrome may getting the Dark mode soon and the icon is kind of hard to see with the dark background:

<img width="39" alt="Screen Shot 2019-03-12 at 22 18 12" src="https://user-images.githubusercontent.com/3784339/54249092-54274400-4515-11e9-8e6c-8e660543341c.png">

I'd be happy to help submit some ideas, but wanted to run it by others first. It looks like the React Chrome extension actually changes with the dark/light toggle

**Comment by xcv58** [comment]
Sure, it would be great if you can provide an icon for the dark mode.

**Comment by xcv58** [comment]
Thanks, @KyleKing I published a new release, it may take an hour for Chrome web store to polulate.

**Comment by KyleKing** [comment]
Thanks! It hit all my browsers this morning
