### ISSUE TITLE
Format Code

### ISSUE THREAD

**Issue by xul8tr** [xcv58/Custom-JavaScript-for-Websites-2#72]
Ability to "Prettify" code

**Comment by xcv58** [comment]
It sounds overkill for me. I think you should use whatever editor you prefer to edit the script and paste it in the extension if it's very long.

**Comment by xul8tr** [comment]
A lot of the time, I'm free handing the in the chrome console then copy/paste. It seems weird that you'd have a lint engine but not a formatter.

**Comment by xcv58** [comment]
The lint tool is a built-in feature of Ace editor https://ace.c9.io. And I don't think it contains native prettify tool for it.

**Comment by xul8tr** [comment]
It looks like there is an extension

[https://stackoverflow.com/questions/31767051/how-do-i-use-beautify-in-ace-editor](https://stackoverflow.com/questions/31767051/how-do-i-use-beautify-in-ace-editor)

**Comment by xcv58** [comment]
It's fixed in v3.4.0

**Comment by xul8tr** [comment]
Nice! Thanks so much!
