### ISSUE TITLE
Allow same script be set in multiple domains.

### ISSUE THREAD

**Issue by marcussacana** [xcv58/Custom-JavaScript-for-Websites-2#872]
Hi, I use this extension to help me reading, I like to set some changes in sites that I read things like the text color, size, background color and etc... 
But after keep using the extension for a while it became a copy and paste of the same script in many sites, and I achieved to reach the storage limit of domains one day.

I think if we can set a same script multiple domains to be actived will increase a my limit in this tool.
Maybe even if it auto detect duplicate scripts and automatically merge in the same one will help too.

ohh, this isn't something really required, but consider a feature to do a early script injecting, currently the scripts seems to be one of the lasts in the page to be executed, then if I need a early injection I need go all my way to create a trampemonkey one... and I like more this tool.

**Comment by marcussacana** [comment]
after look the readme, it seems you aren't the official version, therefore I think I'm using a old version from the store.
So, my issue may be invalid, do you haven't send the tool for edge extension store?, I'm not the original author of a extension but they accept my one like as you can see: https://github.com/marcussacana/VNDB-Extender-2020

**Comment by xcv58** [comment]
> I think if we can set a same script multiple domains to be actived will increase a my limit in this tool.

You can use the regular expression to apply the same script to multiple domains.

And if you just need to customize the styles, I suggest you use this https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en. It's more reliable and specific for update website styles.

> do you haven't send the tool for edge extension store?

No I haven't. I have published another to Edge store but haven't got a chance to upload this one: https://github.com/xcv58/Tab-Manager-v2#download-links

**Comment by marcussacana** [comment]
Fine, thx, but you have builds of the extension signed?
