### ISSUE TITLE
CSS being added as JS and causing Syntax Error

### ISSUE THREAD

**Issue by illtellyoulater** [xcv58/Custom-JavaScript-for-Websites-2#879]
Hello I found that for some reason the CSS code is added as JS, causing Syntax Error in the browser console.
Of course I checked I am saving the code as CSS by selecting "CSS" from the extension code editor drop down menu, but despite this it will be still saved as JS, causing the following error:

`SyntaxError: Unexpected token '.' (at data:text/javascript;base64,Lnl0cC1wYXVzZS1vdmVybGF5LWNvbnRhaW5lciwgLnl0cC1wYXVzZS1vdmVybGF5IHsgCiAgZGlzcGxheTogbm9uZSFpbXBvcnRhbnQKfQ==:1:1) `

I'm using the latest version of the Brave browser on a GNU+Linux system.

I hope you can fix this soon, if you need any other info from me just let me know, thanks!

**Comment by xcv58** [comment]
This extension doesn't support inject CSS. 

> It has nothing to do with CSS but only css syntax highlight, https://github.com/xcv58/Custom-JavaScript-for-Websites-2/issues/58

**Comment by illtellyoulater** [comment]
Sorry, my bad. I got confused after trying other extensions from the google store using exactly the same icon/logo of this one...

**Comment by illtellyoulater** [comment]
> This extension doesn't support inject CSS.
> 
> > It has nothing to do with CSS but only css syntax highlight, #58

What's the point of keeping the CSS drop-down menu entry, then?

It's confusing, as users will expect that the CSS will actually get injected while instead... IT WILL , but  as I said above it gets placed in a JS file causing a Syntax Error in the console when the code is loaded.

If the intention was to not let the user inject CSS, then what was the purpose of having this? 

[src/js/components/ModeSelect.js](https://github.com/xcv58/Custom-JavaScript-for-Websites-2/commit/ab9d33b05df4661d66453bfc28e954b589654ea2#diff-c79e0522fa4181510f1c9bb6ea39e8db49abbf734f63e6e1c40d566037fc9db2)

Just trying to understand...

**Comment by xcv58** [comment]
Some users use JS to inject blocks of CSS and this can help them to better visualize the code.
