### ISSUE TITLE
JS Snippet gets added to every iframe on the specific host

### ISSUE THREAD

**Issue by El-Omar** [xcv58/Custom-JavaScript-for-Websites-2#88]
If you add a snippet, specify a host, the code will be **injected** into that web page and therefore executed.
Now if you have an HTML editor (which depends on an <iframe>), the snippet will ALSO be injected there. So the text or markup that you will write, will also include the JS snippet that you have written for the current host.
This is a serious issue since we work with an admin panel (like a lot of websites) and a CRM and we use the HTML editor quite a lot. We've found that a small snippet was sent with emails that were written in such HTML editors to a lot of clients.
We currently stopped using the extension waiting for a fix.
Thanks in advance, and it would be lovely if you can look into this further.

**Comment by xcv58** [comment]
Thanks for the feedback. I think this can be solved in your code snippet part instead of the extension.

For example, assume your code is:

```js
foo();
```

and it accidentally injects in the iframe one. You can simply wrap your code like this:

```js
if (window === window.top) {
  foo();
}
```

So that your code would execute only within normal tab instead of all iframe.

The iframe detection comes from https://stackoverflow.com/a/925091

There are other ways to detect whether the page inside iframe if it doesn't work.

**Comment by El-Omar** [comment]
Thanks for the reply.
Yes you can track that within the code itself, but wouldn't the whole script still will be included in the other frames?
It wouldn't execute but you still have the script chunk included in the other frames.
That's not very ideal if the script gets included in an email page, because that will nuke your mail score and it will be considered by a lot of engines as a spam mail.
That's one example.

**Comment by xcv58** [comment]
Yes, the scripts code would be injected into the iframes if it matches the rules. 

Could you please tell me how you send out emails? Do you embed the iframe entirely in email?

**Comment by El-Omar** [comment]
We use, as many people do, a WYSIWYG editor to send out emails.
In our CRM, we have a sending-emails-feature that allows users to write their email using a WYSIWYG editor (CKEditor) and then submitting or sending these emails.

How these editors particularly work is as follows:
You have your main iframe (.cke_wysiwyg_frame). Everything that the user writes, modifies or adds, it gets added to the body of that iframe.
Next to the iframe, you have a <textarea> with a value equals to the innerHTML of the body tag from that iframe.

So the structure is as follows:

Your main page.html
| <head>
| </head>
| <body>
|      <textarea>.value = iframe.body.innerHTML
|      <iframe>
| |         <head></head>
| |         <body>
| |              <h1>Hello World</h1>
| |              <script src="cj2scriptData..."></script>
| |         </body>
|       </iframe>
|       <script src="cj2scriptData..."></script>
| </body>

That's how it basically works.
So even if we detect the code, it will still be included in the other iframe and therefore submitted when it's unneeded.

A possible solution will be having a checkbox added to the extension that gives the option to only inject the script in the top-level window and not in the other iframes.

**Comment by xcv58** [comment]
As you mentioned:

> We use, as many people do, a WYSIWYG editor to send out emails.

Could you please give me an example so that I can understand the process?

And AFAIK, directly embed an iframe are incompatible with a lot of email clients: https://www.campaignmonitor.com/blog/email-marketing/2015/07/do-iframes-work-in-email/

If you embed the actual content of the iframe but not the iframe itself, do you have any process to grab the content and embed it in the email body?

**Comment by El-Omar** [comment]
We don't have **literally** an iframe inside our email html, the iframe is what creates the html.

An example:
The editor works based on an iframe. 
The editing process and writing process happens within that iframe window.
When you make a text bold, a strong tag will be added to the body tag of that iframe.

Then the textarea tag **that is outside the iframe (on the same Node level)**, as mentioned previously, will have a value equals to the innerHTML of the body tag of that iframe.

**The textarea is the field that gets submitted. Not the iframe.**

The iframe is just the thing that holds the initial styling / editing of your markup.
But because the textarea tag will take the innerHTML of the body tag of the iframe, it will also take the JS chunk that was injected inside the iframe.

**Comment by xcv58** [comment]
Thanks and I got it. The workflow makes sense. 

I still suggest that you can use a pre-process to wipe the unnecessary script tag before actually sending out the email. It should be easier and error-prone other than relies on the extension to support this use case.

For example, other extensions can inject js code in iframe as well and the option needs to be configured well. A misconfiguration can easily ruin the email again.

**Comment by El-Omar** [comment]
> I still suggest that you can use a pre-process to wipe the unnecessary script tag before actually sending out the email.

That's a great suggestion. If I could I would rewrite the whole backend from scratch, but unfortunately, the fact that I'm using the extension for styling and simple interaction purposes makes you consider the system itself as a whole.

**Comment by El-Omar** [comment]
I will look into this further and maybe implement the feature as a request.
Thank you for the responses and for the help!

**Comment by xcv58** [comment]
You are welcome!
