### ISSUE TITLE
Upgrade to Manifest V3?

### ISSUE THREAD

**Issue by Protbhai** [xcv58/Custom-JavaScript-for-Websites-2#959]
Are you planning to upgrade it to Manifest  V3? As this extension was removed from my chrome today as it said, "This extension is no longer available because it doesn't follow best practices for Chrome extensions."

**Comment by xcv58** [comment]
It seems the extension cannot support Manifest V3, more discussion in:

https://github.com/xcv58/Custom-JavaScript-for-Websites-2/issues/868#issuecomment-1261800301

At this moment, there is no effort to upgrade it to v3.
